export default {
  testRunner: "vitest",
  plugins: ["@stryker-mutator/vitest-runner", "@stryker-mutator/typescript-checker"],
  checkers: ["typescript"],
  tsconfigFile: "tsconfig.json",
  vitest: { configFile: "vitest.mutation.config.ts" },
  mutate: [
    "packages/domain/src/**/*.ts",
    "packages/contracts/src/**/*.ts",
    "!packages/*/src/**/*.test.ts",
  ],
  ignorePatterns: [
    "/*",
    "!/packages",
    "/packages/*",
    "!/packages/domain",
    "!/packages/contracts",
    "!/vitest.mutation.config.ts",
    "!/.github",
    "/.github/*",
    "!/.github/scripts",
    "/.github/scripts/*",
    "!/.github/scripts/without-package-output.mjs",
    "!/.github/scripts/without-package-output.d.mts",
    "!/tsconfig.json",
  ],
  coverageAnalysis: "perTest",
  timeoutMS: 60_000,
  reporters: ["clear-text", "progress"],
  clearTextReporter: { logTests: false },
  thresholds: { high: 100, low: 100, break: 100 },
};
