import type { PermissionKey } from "@purosur/domain";

export const PERMISSION_LABELS = {
  sell_and_charge: "Vender y cobrar, incluido pesar a mano y abrir y cerrar su propia sesión",
  view_sales_history: "Consultar el historial de ventas",
  close_anothers_register_session: "Cerrar la sesión de caja de otra persona",
  reprint_receipt: "Reimprimir un ticket",
  record_cash_in: "Registrar un ingreso de efectivo",
  record_cash_expense: "Registrar un gasto pagado en efectivo",
  withdraw_cash: "Retirar efectivo de la caja",
  override_line_price_or_discount: "Cambiar el precio o aplicar un descuento a una línea",
  apply_total_discount: "Aplicar un descuento sobre el total",
  void_sale: "Anular una venta",
  process_return: "Hacer devoluciones",
  authorize_late_defect_refund: "Autorizar el reembolso de un defecto fuera de plazo",
  confirm_refunds: "Confirmar reembolsos",
  record_initial_inventory: "Inventario inicial",
  view_stock_balances: "Ver saldos",
  perform_stock_counts: "Recuentos",
  adjust_stock: "Ajustes",
  record_stock_losses: "Pérdidas",
  manage_suppliers: "Proveedores",
  manage_purchase_presentations: "Presentaciones de compra",
  record_purchases: "Registrar compras",
  manage_freight: "Flete",
  manage_expiration_dates: "Vencimientos",
  manage_supplier_price_lists: "Cargar y revisar listas de proveedores",
  compare_prices_and_suggest_orders: "Comparación de precios y sugerencia de pedido",
  manage_purchase_orders: "Pedidos",
  receive_purchase_orders: "Recibir pedidos",
  manage_products_and_categories: "Productos y categorías",
  manage_prices_and_review: "Precios y su revisión",
  manage_promotions: "Promociones",
  manage_recipes: "Recetas",
  manage_batches: "Tandas",
  reset_user_pin: "Reiniciar el PIN",
  deactivate_users: "Desactivar usuarios",
  reactivate_users: "Reactivar usuarios",
  correct_register_clock: "Corregir el reloj de la caja",
  view_fiscal_documents: "Ver comprobantes, contingencias y puntos de venta",
  close_fiscal_tasks: "Cerrar tareas fiscales",
  change_fiscal_configuration: "Cambiar la configuración fiscal",
  view_reports: "Ver reportes",
  view_branch_alerts: "Ver alertas del local",
  view_all_alerts: "Ver todas las alertas",
  dismiss_alerts_manually: "Cerrar alertas a mano",
  enroll_register_devices: "Dar de alta cajas",
  revoke_register_devices: "Revocar cajas",
  view_bitlocker_key: "Consultar la clave de BitLocker",
  view_backups_and_rotate_key: "Ver backups y rotar la clave",
  recover_contingency_receipts: "Rescatar tickets de contingencia",
  configure_branch: "Configurar la sucursal",
} satisfies Record<PermissionKey, string>;
